#!/usr/bin/env python3
"""
Unit tests for YouTube Toolkit API endpoints
Tests all major API functionality including CRUD operations, monitoring, and AI features
"""

import pytest
import json
import tempfile
import shutil
from pathlib import Path
from fastapi.testclient import TestClient
import sys
import os

# Add backend to path
sys.path.insert(0, str(Path(__file__).parent.parent / "backend"))

from main import app, metadata_store, OUTPUT_DIR, PROJECT_ROOT


class TestConfig:
    """Test configuration and fixtures"""

    @pytest.fixture
    def client(self):
        """Create test client"""
        return TestClient(app)

    @pytest.fixture
    def temp_data_dir(self, tmp_path):
        """Create temporary data directory"""
        data_dir = tmp_path / "test_channel_data"
        data_dir.mkdir()
        return data_dir

    @pytest.fixture
    def test_config(self, tmp_path):
        """Create test configuration"""
        config = {
            "channels": [
                {
                    "url": "https://www.youtube.com/@TestChannel",
                    "days_back": 7,
                    "languages": ["en"]
                }
            ],
            "settings": {
                "output_directory": str(tmp_path / "channel_data"),
                "default_days_back": 7,
                "default_languages": ["en"]
            },
            "llm": {
                "provider": "openai",
                "model": "gpt-4",
                "apiKey": "test-key"
            }
        }
        return config

    @pytest.fixture
    def sample_transcript(self, tmp_path):
        """Create sample transcript file"""
        channel_dir = tmp_path / "channel_data" / "TestChannel"
        transcripts_dir = channel_dir / "transcripts"
        transcripts_dir.mkdir(parents=True, exist_ok=True)

        transcript_file = transcripts_dir / "2026-04-23_Test_Video.md"
        transcript_content = """# Test Video

**Video URL:** https://www.youtube.com/watch?v=test123
**Video ID:** test123
**Published:** 2026-04-23
**Channel:** TestChannel

---

## Transcript

This is a test transcript content for testing purposes.
It contains multiple lines of text.

---

*Generated by YouTube Toolkit on 2026-04-23 12:00:00*
"""
        transcript_file.write_text(transcript_content)
        return {
            "channel": "TestChannel",
            "filename": "2026-04-23_Test_Video.md",
            "path": transcript_file
        }


class TestHealthEndpoints(TestConfig):
    """Test health check and basic endpoints"""

    def test_health_check(self, client):
        """Test GET /api/health"""
        response = client.get("/api/health")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "healthy"
        assert "version" in data

    def test_root_redirect(self, client):
        """Test root endpoint redirects to frontend"""
        response = client.get("/", follow_redirects=False)
        # Should either return 200 or redirect
        assert response.status_code in [200, 307, 308]


class TestStatsEndpoints(TestConfig):
    """Test statistics endpoints"""

    def test_get_stats_empty(self, client, monkeypatch):
        """Test GET /api/stats with no data"""
        # Mock empty directory
        with tempfile.TemporaryDirectory() as tmpdir:
            monkeypatch.setattr("main.OUTPUT_DIR", tmpdir)
            response = client.get("/api/stats")
            assert response.status_code == 200
            data = response.json()
            assert data["total_channels"] == 0
            assert data["total_transcripts"] == 0
            assert data["total_size_mb"] == 0

    def test_get_tree_empty(self, client, monkeypatch):
        """Test GET /api/tree with no data"""
        with tempfile.TemporaryDirectory() as tmpdir:
            monkeypatch.setattr("main.OUTPUT_DIR", tmpdir)
            response = client.get("/api/tree")
            assert response.status_code == 200
            data = response.json()
            assert isinstance(data, list)
            assert len(data) == 0

    def test_get_tree_with_sort(self, client):
        """Test GET /api/tree with sort parameter"""
        response = client.get("/api/tree?sort=asc")
        assert response.status_code == 200

        response = client.get("/api/tree?sort=desc")
        assert response.status_code == 200


class TestConfigEndpoints(TestConfig):
    """Test configuration endpoints"""

    def test_get_config(self, client, monkeypatch, test_config, tmp_path):
        """Test GET /api/config"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))

        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        response = client.get("/api/config")
        assert response.status_code == 200
        data = response.json()
        assert "channels" in data
        assert "settings" in data

    def test_add_channel(self, client, monkeypatch, tmp_path):
        """Test POST /api/channels"""
        config_file = tmp_path / "test_config.json"
        initial_config = {
            "channels": [],
            "settings": {}
        }
        config_file.write_text(json.dumps(initial_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        new_channel = {
            "url": "https://www.youtube.com/@NewChannel",
            "days_back": 14,
            "languages": ["en"]
        }

        response = client.post("/api/channels", json=new_channel)
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True

    def test_update_channel(self, client, monkeypatch, test_config, tmp_path):
        """Test PUT /api/channels/{index}"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        updated_channel = {
            "url": "https://www.youtube.com/@UpdatedChannel",
            "days_back": 30,
            "languages": ["en", "es"]
        }

        response = client.put("/api/channels/0", json=updated_channel)
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True

    def test_update_channel_invalid_index(self, client, monkeypatch, test_config, tmp_path):
        """Test PUT /api/channels/{index} with invalid index"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        response = client.put("/api/channels/999", json={"url": "test"})
        assert response.status_code == 404

    def test_delete_channel_config(self, client, monkeypatch, test_config, tmp_path):
        """Test DELETE /api/channels/{index}"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        response = client.delete("/api/channels/0")
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True


class TestTranscriptEndpoints(TestConfig):
    """Test transcript CRUD endpoints"""

    def test_get_transcript_not_found(self, client):
        """Test GET /api/transcript/{channel}/{filename} - not found"""
        response = client.get("/api/transcript/NonExistent/file.md")
        assert response.status_code == 404

    def test_get_transcript_success(self, client, monkeypatch, sample_transcript, tmp_path):
        """Test GET /api/transcript/{channel}/{filename} - success"""
        monkeypatch.setattr("main.OUTPUT_DIR", str(tmp_path / "channel_data"))

        response = client.get(
            f"/api/transcript/{sample_transcript['channel']}/{sample_transcript['filename']}"
        )
        assert response.status_code == 200
        data = response.json()
        assert data["channel"] == sample_transcript["channel"]
        assert data["filename"] == sample_transcript["filename"]
        assert "content" in data
        assert "Test Video" in data["content"]

    def test_get_transcript_path_traversal(self, client):
        """Test GET /api/transcript - path traversal attempt"""
        response = client.get("/api/transcript/test/../../../etc/passwd")
        assert response.status_code in [403, 404]

    def test_delete_transcript_not_found(self, client):
        """Test DELETE /api/transcript/{channel}/{filename} - not found"""
        response = client.delete("/api/transcript/NonExistent/file.md")
        assert response.status_code == 404

    def test_delete_transcript_success(self, client, monkeypatch, sample_transcript, tmp_path):
        """Test DELETE /api/transcript/{channel}/{filename} - success"""
        monkeypatch.setattr("main.OUTPUT_DIR", str(tmp_path / "channel_data"))

        response = client.delete(
            f"/api/transcript/{sample_transcript['channel']}/{sample_transcript['filename']}"
        )
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["deleted_count"] > 0 or len(data["deleted_files"]) > 0

        # Verify file is deleted
        assert not sample_transcript["path"].exists()


class TestChannelDataEndpoints(TestConfig):
    """Test channel data management endpoints"""

    def test_delete_channel_data_not_found(self, client):
        """Test DELETE /api/channel/{channel} - not found"""
        response = client.delete("/api/channel/NonExistentChannel")
        assert response.status_code == 404

    def test_delete_channel_data_success(self, client, monkeypatch, sample_transcript, tmp_path):
        """Test DELETE /api/channel/{channel} - success"""
        monkeypatch.setattr("main.OUTPUT_DIR", str(tmp_path / "channel_data"))

        response = client.delete(f"/api/channel/{sample_transcript['channel']}")
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["channel"] == sample_transcript["channel"]
        assert data["deleted_count"] >= 0

        # Verify directory is deleted
        channel_dir = tmp_path / "channel_data" / sample_transcript["channel"]
        assert not channel_dir.exists()


class TestMetadataEndpoints(TestConfig):
    """Test metadata management endpoints"""

    def test_get_metadata_not_found(self, client):
        """Test GET /api/metadata/transcript/{channel}/{filename} - not found"""
        response = client.get("/api/metadata/transcript/NonExistent/file.md")
        assert response.status_code == 404

    def test_update_keywords(self, client, monkeypatch, sample_transcript, tmp_path):
        """Test POST /api/metadata/transcript/{channel}/{filename}/keywords"""
        # Initialize metadata first
        from transcript_metadata import TranscriptMetadata

        metadata = TranscriptMetadata(
            channel=sample_transcript["channel"],
            filename=sample_transcript["filename"],
            title="Test Video",
            date="2026-04-23"
        )
        metadata_store.set(metadata)

        keywords = ["AI", "machine learning", "testing"]
        response = client.post(
            f"/api/metadata/transcript/{sample_transcript['channel']}/{sample_transcript['filename']}/keywords",
            json=keywords
        )
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["keywords"] == keywords

    def test_update_summary(self, client, monkeypatch, sample_transcript):
        """Test POST /api/metadata/transcript/{channel}/{filename}/summary"""
        from transcript_metadata import TranscriptMetadata

        metadata = TranscriptMetadata(
            channel=sample_transcript["channel"],
            filename=sample_transcript["filename"],
            title="Test Video",
            date="2026-04-23"
        )
        metadata_store.set(metadata)

        response = client.post(
            f"/api/metadata/transcript/{sample_transcript['channel']}/{sample_transcript['filename']}/summary",
            json={
                "summary": "This is a test summary",
                "model": "gpt-4"
            }
        )
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True


class TestMonitoringEndpoints(TestConfig):
    """Test monitoring endpoints"""

    def test_get_monitor_status(self, client):
        """Test GET /api/monitor/status"""
        response = client.get("/api/monitor/status")
        assert response.status_code == 200
        data = response.json()
        assert "running" in data
        assert "progress" in data

    def test_start_monitoring_no_channels(self, client, monkeypatch, tmp_path):
        """Test POST /api/monitor/start - no channels configured"""
        config_file = tmp_path / "empty_config.json"
        config_file.write_text(json.dumps({"channels": []}))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        response = client.post("/api/monitor/start")
        assert response.status_code == 400

    def test_start_monitoring_already_running(self, client, monkeypatch, test_config, tmp_path):
        """Test POST /api/monitor/start - already running"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        # Mock monitoring as already running
        from main import monitoring_status
        monitoring_status["running"] = True

        response = client.post("/api/monitor/start")
        assert response.status_code == 400

        # Reset
        monitoring_status["running"] = False


class TestLLMEndpoints(TestConfig):
    """Test LLM/AI endpoints"""

    def test_get_llm_config(self, client, monkeypatch, test_config, tmp_path):
        """Test GET /api/llm/config"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps(test_config))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        response = client.get("/api/llm/config")
        assert response.status_code == 200
        data = response.json()
        assert "provider" in data
        assert "model" in data
        # API key should not be exposed
        assert "apiKey" not in data or data.get("hasApiKey") is not None

    def test_summarize_stream_transcript_not_found(self, client):
        """Test GET /api/transcript/{channel}/{filename}/summarize/stream - not found"""
        response = client.get("/api/transcript/NonExistent/file.md/summarize/stream")
        # Stream endpoint may return 200 with error in stream
        assert response.status_code in [200, 404]


class TestSecurityValidation(TestConfig):
    """Test security and input validation"""

    def test_path_traversal_protection(self, client):
        """Test path traversal attempts are blocked"""
        malicious_paths = [
            "../../../etc/passwd",
            "..%2F..%2F..%2Fetc%2Fpasswd",
            "test/../../sensitive",
        ]

        for path in malicious_paths:
            response = client.get(f"/api/transcript/{path}")
            assert response.status_code in [403, 404]

    def test_invalid_json_handling(self, client):
        """Test invalid JSON in POST requests"""
        response = client.post(
            "/api/channels",
            data="invalid json",
            headers={"Content-Type": "application/json"}
        )
        assert response.status_code == 422  # Unprocessable Entity

    def test_missing_required_fields(self, client, monkeypatch, tmp_path):
        """Test POST with missing required fields"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps({"channels": []}))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        # Missing required 'url' field
        response = client.post("/api/channels", json={"days_back": 7})
        assert response.status_code == 422


class TestErrorHandling(TestConfig):
    """Test error handling and edge cases"""

    def test_404_on_invalid_endpoint(self, client):
        """Test 404 for non-existent endpoints"""
        response = client.get("/api/nonexistent")
        assert response.status_code == 404

    def test_method_not_allowed(self, client):
        """Test 405 for wrong HTTP method"""
        response = client.post("/api/stats")
        assert response.status_code == 405

    def test_large_payload_handling(self, client, monkeypatch, tmp_path):
        """Test handling of large payloads"""
        config_file = tmp_path / "test_config.json"
        config_file.write_text(json.dumps({"channels": []}))
        monkeypatch.setattr("main.CONFIG_FILE", str(config_file))

        # Create large keyword list
        large_keywords = ["keyword"] * 10000
        response = client.post(
            "/api/metadata/transcript/test/test.md/keywords",
            json=large_keywords
        )
        # Should handle gracefully (either accept or reject with proper error)
        assert response.status_code in [200, 404, 413, 422]


if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
