#!/usr/bin/env python3
"""
YouTube Channel Monitor
Monitors YouTube channels for new videos and extracts their scripts.
"""

import os
import re
from datetime import datetime, timedelta
from typing import List, Dict, Optional
from pathlib import Path

from .channel_lister import YouTubeChannelLister
from .downloader import SubtitleDownloader
from .converter import SubtitleToText


class ChannelMonitor:
    """Monitor YouTube channels and extract video scripts."""

    def __init__(self, output_base_dir: str = "channel_data"):
        """
        Initialize the channel monitor.

        Args:
            output_base_dir: Base directory for storing channel data
        """
        self.output_base_dir = output_base_dir
        self.lister = YouTubeChannelLister()
        self.downloader = SubtitleDownloader()
        self.converter = SubtitleToText()
        os.makedirs(output_base_dir, exist_ok=True)

    def sanitize_filename(self, filename: str) -> str:
        """Sanitize filename by removing invalid characters."""
        filename = re.sub(r'[<>:"/\\|?*]', '', filename)
        filename = re.sub(r'\s+', '_', filename)
        filename = filename[:200]  # Limit length
        return filename

    def get_channel_name(self, channel_url: str) -> str:
        """Extract channel name from URL."""
        patterns = [
            r'youtube\.com/@([^/?]+)',
            r'youtube\.com/c/([^/?]+)',
            r'youtube\.com/user/([^/?]+)',
            r'youtube\.com/channel/([^/?]+)',
        ]

        for pattern in patterns:
            match = re.search(pattern, channel_url)
            if match:
                return self.sanitize_filename(match.group(1))

        return "unknown_channel"

    def filter_recent_videos(
        self,
        videos: List[Dict],
        days: int = 7
    ) -> List[Dict]:
        """
        Filter videos published within the last N days.

        Args:
            videos: List of video dictionaries
            days: Number of days to look back

        Returns:
            Filtered list of recent videos
        """
        cutoff_date = datetime.now() - timedelta(days=days)
        recent_videos = []

        for video in videos:
            try:
                pub_date = datetime.strptime(
                    video['published_at'],
                    '%Y-%m-%dT%H:%M:%SZ'
                )
                if pub_date >= cutoff_date:
                    recent_videos.append(video)
            except (ValueError, KeyError):
                continue

        return recent_videos

    def create_annotated_transcript(
        self,
        video: Dict,
        transcript_text: str,
        output_path: str
    ) -> None:
        """
        Create an annotated transcript file with metadata.

        Args:
            video: Video metadata dictionary
            transcript_text: The transcript text
            output_path: Output file path
        """
        annotation = f"""# {video['title']}

**Video URL:** {video['url']}
**Video ID:** {video['video_id']}
**Published:** {video['published_date']}
**Channel:** {video.get('channel_title', 'N/A')}

---

## Transcript

{transcript_text}

---

*Generated by YouTube Toolkit on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(annotation)

    def check_transcript_exists(
        self,
        video: Dict,
        transcripts_dir: str
    ) -> bool:
        """
        Check if transcript already exists for a video.

        Args:
            video: Video metadata dictionary
            transcripts_dir: Directory containing transcripts

        Returns:
            True if transcript exists, False otherwise
        """
        safe_title = self.sanitize_filename(video['title'])
        transcript_filename = f"{video['published_date'][:10]}_{safe_title}.md"
        transcript_path = os.path.join(transcripts_dir, transcript_filename)
        return os.path.exists(transcript_path)

    def process_channel(
        self,
        channel_url: str,
        days_back: int = 7,
        languages: Optional[List[str]] = None
    ) -> Dict:
        """
        Process a YouTube channel and extract recent video scripts.

        Args:
            channel_url: YouTube channel URL
            days_back: Number of days to look back for videos
            languages: List of subtitle language codes (default: ['en'])

        Returns:
            Dictionary with processing results
        """
        if languages is None:
            languages = ['en']

        result = {
            'success': False,
            'channel_url': channel_url,
            'channel_name': None,
            'videos_found': 0,
            'videos_processed': 0,
            'videos_skipped': 0,
            'transcripts_created': [],
            'errors': []
        }

        try:
            # Get channel name and create directory structure
            channel_name = self.get_channel_name(channel_url)
            result['channel_name'] = channel_name

            channel_dir = os.path.join(self.output_base_dir, channel_name)
            subtitles_dir = os.path.join(channel_dir, 'subtitles')
            transcripts_dir = os.path.join(channel_dir, 'transcripts')

            os.makedirs(subtitles_dir, exist_ok=True)
            os.makedirs(transcripts_dir, exist_ok=True)

            print(f"\n{'='*80}")
            print(f"Processing Channel: {channel_name}")
            print(f"URL: {channel_url}")
            print(f"Looking back: {days_back} days")
            print(f"{'='*80}\n")

            # Step 1: Get all videos from channel
            print("Step 1: Fetching videos from channel...")
            all_videos = self.lister.get_channel_videos(channel_url, max_results=50)

            # Step 2: Filter for recent videos
            print(f"Step 2: Filtering for videos from last {days_back} days...")
            recent_videos = self.filter_recent_videos(all_videos, days_back)
            result['videos_found'] = len(recent_videos)

            if not recent_videos:
                print(f"No videos found in the last {days_back} days.")
                result['success'] = True
                return result

            print(f"Found {len(recent_videos)} recent video(s)\n")

            # Step 3: Process each video
            for i, video in enumerate(recent_videos, 1):
                print(f"\n[{i}/{len(recent_videos)}] Processing: {video['title']}")
                print(f"Published: {video['published_date']}")

                # Check if transcript already exists
                if self.check_transcript_exists(video, transcripts_dir):
                    print(f"  ⏭  Transcript already exists, skipping...")
                    result['videos_skipped'] += 1
                    continue

                try:
                    # Download subtitles
                    self.downloader.output_dir = subtitles_dir
                    download_result = self.downloader.download_subtitles(
                        video_url=video['video_id'],
                        languages=languages,
                        format='srt'
                    )

                    if not download_result['success']:
                        error_msg = f"Failed to download subtitles: {download_result.get('error', 'Unknown error')}"
                        print(f"  ✗ {error_msg}")
                        result['errors'].append({
                            'video': video['title'],
                            'error': error_msg
                        })
                        continue

                    if not download_result['files']:
                        error_msg = "No subtitle files were downloaded"
                        print(f"  ✗ {error_msg}")
                        result['errors'].append({
                            'video': video['title'],
                            'error': error_msg
                        })
                        continue

                    print(f"  ✓ Downloaded subtitles")

                    # Convert subtitle to text
                    subtitle_file = download_result['files'][0]
                    transcript_text = self.converter.convert_file(
                        subtitle_file,
                        output_path=None,
                        detect_speakers=False
                    )

                    print(f"  ✓ Converted to text ({len(transcript_text)} characters)")

                    # Create annotated transcript
                    safe_title = self.sanitize_filename(video['title'])
                    transcript_filename = f"{video['published_date'][:10]}_{safe_title}.md"
                    transcript_path = os.path.join(transcripts_dir, transcript_filename)

                    self.create_annotated_transcript(video, transcript_text, transcript_path)
                    print(f"  ✓ Created transcript: {transcript_filename}")

                    result['transcripts_created'].append(transcript_path)
                    result['videos_processed'] += 1

                except Exception as e:
                    error_msg = str(e)
                    print(f"  ✗ Error: {error_msg}")
                    result['errors'].append({
                        'video': video['title'],
                        'error': error_msg
                    })

            result['success'] = True

        except Exception as e:
            result['errors'].append({
                'video': 'channel_processing',
                'error': str(e)
            })

        return result

    def process_multiple_channels(
        self,
        channel_urls: List[str],
        days_back: int = 7,
        languages: Optional[List[str]] = None
    ) -> List[Dict]:
        """
        Process multiple YouTube channels.

        Args:
            channel_urls: List of YouTube channel URLs
            days_back: Number of days to look back
            languages: List of subtitle language codes

        Returns:
            List of processing results for each channel
        """
        results = []

        for i, channel_url in enumerate(channel_urls, 1):
            print(f"\n\n{'#'*80}")
            print(f"Channel {i}/{len(channel_urls)}")
            print(f"{'#'*80}")

            result = self.process_channel(channel_url, days_back, languages)
            results.append(result)

        return results

    def generate_summary_report(self, results: List[Dict]) -> str:
        """
        Generate a summary report of processing results.

        Args:
            results: List of processing results

        Returns:
            Formatted summary report
        """
        report_lines = [
            "\n" + "="*80,
            "PROCESSING SUMMARY",
            "="*80,
            ""
        ]

        total_videos_found = sum(r['videos_found'] for r in results)
        total_videos_processed = sum(r['videos_processed'] for r in results)
        total_transcripts = sum(len(r['transcripts_created']) for r in results)
        total_errors = sum(len(r['errors']) for r in results)

        total_videos_skipped = sum(r.get('videos_skipped', 0) for r in results)

        report_lines.extend([
            f"Channels processed: {len(results)}",
            f"Videos found: {total_videos_found}",
            f"Videos skipped (already processed): {total_videos_skipped}",
            f"Videos processed: {total_videos_processed}",
            f"Transcripts created: {total_transcripts}",
            f"Errors: {total_errors}",
            ""
        ])

        for result in results:
            if result['success']:
                report_lines.extend([
                    f"\n✓ {result['channel_name']}",
                    f"  Videos found: {result['videos_found']}",
                    f"  Videos skipped: {result.get('videos_skipped', 0)}",
                    f"  Videos processed: {result['videos_processed']}",
                    f"  Transcripts: {len(result['transcripts_created'])}"
                ])

                if result['errors']:
                    report_lines.append(f"  Errors: {len(result['errors'])}")
                    for error in result['errors'][:3]:  # Show first 3 errors
                        report_lines.append(f"    - {error['video']}: {error['error'][:50]}")
            else:
                report_lines.extend([
                    f"\n✗ {result.get('channel_name', 'Unknown channel')}",
                    f"  Failed: {result['errors'][0]['error'] if result['errors'] else 'Unknown error'}"
                ])

        report_lines.append("\n" + "="*80 + "\n")

        return "\n".join(report_lines)


def main():
    """CLI entry point for channel monitoring."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python -m youtube_toolkit.monitor <channel_url> [days_back] [languages]")
        print("\nExamples:")
        print("  python -m youtube_toolkit.monitor https://www.youtube.com/@channelname")
        print("  python -m youtube_toolkit.monitor https://www.youtube.com/@channelname 7")
        print("  python -m youtube_toolkit.monitor https://www.youtube.com/@channelname 7 en,es")
        sys.exit(1)

    channel_url = sys.argv[1]
    days_back = int(sys.argv[2]) if len(sys.argv) > 2 else 7
    languages = sys.argv[3].split(',') if len(sys.argv) > 3 else ['en']

    monitor = ChannelMonitor()
    result = monitor.process_channel(channel_url, days_back, languages)

    print(monitor.generate_summary_report([result]))

    sys.exit(0 if result['success'] else 1)


if __name__ == "__main__":
    main()
